spring:
  thymeleaf:
    mode: HTML
    prefix: classpath:/templates/
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: aa94987366
    url: jdbc:mysql://localhost:3306/petclinic
  messages:
    basename: messages/messages

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*.xml